project:
  type: website
  output-dir: docs
  # favicon: logo.png

website:
  title: "deepSSF"
  page-navigation: true
  navbar:
    # background: "#FCAB64"
    left:

      - text: "Home"
        href: index.qmd
      - text: "Getting Started"
        href: getting_started.qmd
      - text: "Study System"
        href: study_system.qmd
      - text: "Data Preparation"
        href: data_preparation.qmd
      - text: "Model Training"
        href: model_training.qmd
      - text: "Predictions"
        href: predictions.qmd
      - text: "Inference"
        href: inference.qmd
      - text: "Validation"
        href: validation.qmd

      # - href: index.qmd
      #   text: Home
      # - href: study_system.qmd
      #   text: Study System
      # - href: step_selection_intuition.qmd
      #   text: Step Selection Intuition
      # - href: deepSSF_model_overview.qmd
      #   text: deepSSF Model Overview
      # - href: deep_learning_concepts.qmd
      #   text: Deep Learning Concepts

    right:
    - text: "Website"
      href: https://swforrest.github.io
    - icon: github
      href: https://github.com/swforrest/deepSSF
    - icon: envelope-at-fill
      href: mailto:scottwforrest@gmail.com
    - icon: linkedin
      href: https://www.linkedin.com/in/swforrest/
    - text: "Bluesky"
      href: https://bsky.app/profile/scottwilliamf.bsky.social

  sidebar:

      - title: "Getting Started"
        style: floating
        contents: 
          - getting_started.qmd
          - python_installation.qmd
          - deep_learning_concepts.qmd
          - step_selection_intuition.qmd
          - deepSSF_model_overview.qmd

      # - title: "Deep Learning Concepts"
      #   style: floating
      #   contents: 
      #     - deep_learning_concepts.qmd
      #     - convolutional_layers.qmd
      #     - feedforward_layers.qmd
      #     - max_pooling.qmd
      #     - activation_functions.qmd
      #     - backpropagation.qmd
      
      - title: "Study System"
        contents:
          - study_system.qmd

      - title: "Data Preparation"
        contents:
          - data_preparation.qmd
          - deepSSF_data_prep_id.qmd
          - deepSSF_data_prep_S2_id.qmd

      - title: "Model Training"
        contents:
          - model_training.qmd
          - Python/deepSSF_train.ipynb
          - Python/deepSSF_train_S2.ipynb

      - title: "Predictions"
        contents:
          - predictions.qmd
          - Python/deepSSF_simulations.ipynb
          - Python/deepSSF_simulations_S2.ipynb
          - Python/deepSSF_landscape_preds.ipynb
          - Python/deepSSF_landscape_preds_S2.ipynb

      - title: "Inference"
        contents:
          - inference.qmd
          - deepSSF_assessing_trajectories.qmd
          - deepSSF_habitat_selection.qmd

      - title: "Validation"
        contents:
          - validation.qmd
          - Python/deepSSF_next_step_validation.ipynb
          - Python/deepSSF_next_step_validation_S2.ipynb
          - ssf_model_fit_id.qmd
          - ssf_validation.qmd
          - validation_comparison.qmd

#   sidebar:
#     style: "floating"
#     search: false
#     contents:
#       - section: "Data Preparation"
#         contents:
#           - deepSSF_data_prep_id.qmd
#           - deepSSF_data_prep_S2_id.qmd
#       - section: "Model Training"
#         contents:
#           - Python/deepSSF_train.ipynb
#           - Python/deepSSF_train_S2.ipynb
#       - section: "Generating simulations"
#         contents:
#           - Python/deepSSF_simulations.ipynb
#           - Python/deepSSF_simulations_S2.ipynb
#           - deepSSF_assessing_trajectories.qmd
#       - section: "Landscape predictions"
#         contents:
#           - Python/deepSSF_landscape_preds.ipynb
#           - Python/deepSSF_landscape_preds_S2.ipynb
#           - deepSSF_habitat_selection.qmd
#       - section: "Next-Step Validation"
#         contents:
#           - Python/deepSSF_next_step_validation.ipynb
#           - Python/deepSSF_next_step_validation_S2.ipynb
#           - ssf_model_fit_id.qmd
#           - ssf_validation.qmd
#           - validation_comparison.qmd
# page-navigation: true

  page-footer:
    background: light
    center:
      - text: "Website"
        href: https://swforrest.github.io
      - icon: envelope-at-fill
        href: mailto:scottwforrest@gmail.com
      - icon: github
        href: https://github.com/swforrest
      - icon: linkedin
        href: https://www.linkedin.com/in/swforrest/
      - text: "Bluesky"
        href: https://bsky.app/profile/scottwilliamf.bsky.social
      - text: "Scholar"
        href: https://scholar.google.com.au/citations?user=ECYMO3YAAAAJ&hl=en&authuser=1

format:
  html:
    theme: yeti
    # fontcolor: "#BF3100"
    # linkcolor: "#42CAFD"
    css: styles.css
    toc: true

execute:
  freeze: auto