project:
  type: website
  output-dir: docs

website:
  title: "deepSSF"
  navbar:
    # background: "#FCAB64"
    left:
      - href: index.qmd
        text: Home
      - href: study_system.qmd
        text: Study System
      - href: step_selection_intuition.qmd
        text: Step Selection Intuition
      - href: deepSSF_model_overview.qmd
        text: deepSSF Model Overview
      - href: deep_learning_concepts.qmd
        text: Deep Learning Concepts

    right:
    - icon: github
      href: https://github.com/swforrest/deepSSF
    - icon: envelope-at-fill
      href: mailto:scottwforrest@gmail.com
    - icon: linkedin
      href: https://www.linkedin.com/in/swforrest/

  sidebar:
    style: "floating"
    search: false
    contents:
      - section: "Data Preparation"
        contents:
          - deepSSF_data_prep_id.qmd
          - deepSSF_data_prep_S2_id.qmd
      - section: "Model Training"
        contents:
          - Python/deepSSF_train.ipynb
          - Python/deepSSF_train_S2.ipynb
      - section: "Generating simulations"
        contents:
          - Python/deepSSF_simulations.ipynb
          - Python/deepSSF_simulations_S2.ipynb
          - deepSSF_assessing_trajectories.qmd
      - section: "Landscape predictions"
        contents:
          - Python/deepSSF_landscape_preds.ipynb
          - Python/deepSSF_landscape_preds_S2.ipynb
          - deepSSF_habitat_selection.qmd
      - section: "Next-Step Validation"
        contents:
          - Python/deepSSF_next_step_validation.ipynb
          - Python/deepSSF_next_step_validation_S2.ipynb
          - ssf_model_fit_id.qmd
          - ssf_validation.qmd
          - validation_comparison.qmd
page-navigation: true

format:
  html:
    theme: yeti
    # fontcolor: "#BF3100"
    # linkcolor: "#42CAFD"
    css: styles.css
    toc: true

execute:
  freeze: auto