% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}
\usepackage{xcolor}
\usepackage[top=30mm,left=30mm]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\usepackage{longtable,booktabs,array}
\newcounter{none} % for unnumbered tables
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother





\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={deepSSF Data Prep},
  pdfauthor={Scott Forrest},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{deepSSF Data Prep}
\author{Scott Forrest}
\date{2026-05-26}
\begin{document}
\maketitle
\begin{abstract}
Here we prepare the data for fitting a deepSSF model. We load the GPS
data and tidy it, create a trajectory object containing a series of
steps and read in the environmental layers. For each observed step we
crop out local subsets of the environmental layers, centred on the
step's location. For every step we will then have the surrounding
environmental information stored as a stack of small rasters, with the
`target' of what we're trying to predict (the actual location of the
next step) as a raster layer as well, with all cells being 0 except the
observed next location, which is 1. These, along with temporal
covariates and the previous bearing, will be the input data for the
deepSSF model.
\end{abstract}

\renewcommand*\contentsname{Table of contents}
{
\setcounter{tocdepth}{3}
\tableofcontents
}

\subsection{Loading packages}\label{loading-packages}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\NormalTok{packages }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"amt"}\NormalTok{, }\StringTok{"sf"}\NormalTok{, }\StringTok{"terra"}\NormalTok{, }\StringTok{"beepr"}\NormalTok{, }\StringTok{"tictoc"}\NormalTok{)}
\FunctionTok{walk}\NormalTok{(packages, require, }\AttributeTok{character.only =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\subsection{Import data}\label{import-data}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{buffalo }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"data/buffalo.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
New names:
Rows: 133161 Columns: 11
-- Column specification
-------------------------------------------------------- Delimiter: "," chr
(3): node, dates, DateTime dbl (7): ...1, lat, lon, height, accuracy, heading,
speed dttm (1): timestamp
i Use `spec()` to retrieve the full column specification for this data. i
Specify the column types or set `show_col_types = FALSE` to quiet this message.
* `` -> `...1`
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(buffalo)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tibble: 6 x 11
   ...1 timestamp             lat   lon height accuracy heading speed node 
  <dbl> <dttm>              <dbl> <dbl>  <dbl>    <dbl>   <dbl> <dbl> <chr>
1   169 2018-07-25 00:04:02 -12.3  134.   91.3      977     0   0     2005 
2   170 2018-07-25 01:04:23 -12.3  134.   92.1      704    77.0 0.034 2005 
3   171 2018-07-25 02:04:39 -12.3  134.   95.2     1105   129.  0.008 2005 
4   172 2018-07-25 03:04:17 -12.3  134.  104.       865     0   0.013 2005 
5   173 2018-07-25 04:04:39 -12.3  134.   85.5      711   231.  0.01  2005 
6   174 2018-07-25 05:04:27 -12.3  134.   95.8      780   207.  0.012 2005 
# i 2 more variables: dates <chr>, DateTime <chr>
\end{verbatim}

\subsection{Tidy data}\label{tidy-data}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# remove individuals that have poor data quality or less than about 3 months of data. }
\CommentTok{\# The "2014.GPS\_COMPACT copy.csv" string is a duplicate of ID 2024, so we also exclude it}
\NormalTok{buffalo }\OtherTok{\textless{}{-}}\NormalTok{ buffalo }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\NormalTok{node }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"2014.GPS\_COMPACT copy.csv"}\NormalTok{, }
                                           \CommentTok{\# 2005, 2014, 2018, 2021, 2022, 2024,}
                                           \DecValTok{2029}\NormalTok{, }\DecValTok{2043}\NormalTok{, }\DecValTok{2265}\NormalTok{, }\DecValTok{2284}\NormalTok{, }\DecValTok{2346}\NormalTok{, }\DecValTok{2354}\NormalTok{))}

\CommentTok{\# arrange by time and exclude any duplicate timestamps (within the same individual\textquotesingle{}s data)}
\NormalTok{buffalo }\OtherTok{\textless{}{-}}\NormalTok{ buffalo }\SpecialCharTok{\%\textgreater{}\%}  
  \FunctionTok{group\_by}\NormalTok{(node) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{arrange}\NormalTok{(DateTime, }\AttributeTok{.by\_group =}\NormalTok{ T) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{distinct}\NormalTok{(DateTime, }\AttributeTok{.keep\_all =}\NormalTok{ T) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{arrange}\NormalTok{(node) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{ID =}\NormalTok{ node)}

\CommentTok{\# keep only the relevant columns}
\NormalTok{buffalo\_clean }\OtherTok{\textless{}{-}}\NormalTok{ buffalo[, }\FunctionTok{c}\NormalTok{(}\DecValTok{12}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{3}\NormalTok{)]}

\CommentTok{\# rename the columns}
\FunctionTok{colnames}\NormalTok{(buffalo\_clean) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"id"}\NormalTok{, }\StringTok{"time"}\NormalTok{, }\StringTok{"lon"}\NormalTok{, }\StringTok{"lat"}\NormalTok{)}

\CommentTok{\# convert the time to the correct timezone}
\FunctionTok{attr}\NormalTok{(buffalo\_clean}\SpecialCharTok{$}\NormalTok{time, }\StringTok{"tzone"}\NormalTok{) }\OtherTok{\textless{}{-}} \StringTok{"Australia/Queensland"}
\FunctionTok{head}\NormalTok{(buffalo\_clean)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tibble: 6 x 4
  id    time                  lon   lat
  <chr> <dttm>              <dbl> <dbl>
1 2005  2019-01-01 11:01:14  134. -12.3
2 2005  2019-01-01 21:00:59  134. -12.3
3 2005  2019-01-01 22:01:15  134. -12.3
4 2005  2019-01-01 23:01:28  134. -12.3
5 2005  2019-01-02 00:01:12  134. -12.3
6 2005  2019-01-02 03:00:36  134. -12.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# check timezone}
\FunctionTok{tz}\NormalTok{(buffalo\_clean}\SpecialCharTok{$}\NormalTok{time)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "Australia/Queensland"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# create a vector of the unique ids for indexing later}
\NormalTok{buffalo\_ids }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(buffalo\_clean}\SpecialCharTok{$}\NormalTok{id)}
\end{Highlighting}
\end{Shaded}

\subsection{Create a subset of the data to export for testing the
deepSSF
package}\label{create-a-subset-of-the-data-to-export-for-testing-the-deepssf-package}

We'll select the ID 2005, as that was used for training the model in the
MEE paper

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{buffalo\_clean\_2005 }\OtherTok{\textless{}{-}}\NormalTok{ buffalo\_clean }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(id }\SpecialCharTok{==} \DecValTok{2005}\NormalTok{) }

\CommentTok{\# convert to sf object and transform to the same projection as the covariates (GDA94 / Geoscience Australia Lambert, EPSG:3112)}
\NormalTok{buffalo\_clean\_2005\_sf }\OtherTok{\textless{}{-}}\NormalTok{ buffalo\_clean\_2005 }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{st\_as\_sf}\NormalTok{(}\AttributeTok{coords =} \FunctionTok{c}\NormalTok{(}\StringTok{"lon"}\NormalTok{, }\StringTok{"lat"}\NormalTok{), }\AttributeTok{crs =} \DecValTok{4326}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{st\_transform}\NormalTok{(}\AttributeTok{crs =} \DecValTok{3112}\NormalTok{) }

\CommentTok{\# add the coordinates back to the data frame}
\NormalTok{buffalo\_clean\_2005\_coords }\OtherTok{\textless{}{-}}\NormalTok{ buffalo\_clean\_2005\_sf }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{st\_coordinates}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{as.data.frame}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{rename}\NormalTok{(}\AttributeTok{x =}\NormalTok{ X, }\AttributeTok{y =}\NormalTok{ Y)}

\NormalTok{buffalo\_clean\_2005\_proj }\OtherTok{\textless{}{-}}\NormalTok{ buffalo\_clean\_2005 }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{bind\_cols}\NormalTok{(buffalo\_clean\_2005\_coords) }\SpecialCharTok{\%\textgreater{}\%} 
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(id, time, x, y)}

\NormalTok{buffalo\_clean\_2005\_proj }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{write\_csv}\NormalTok{(}\StringTok{"data/buffalo\_djelk\_id2005.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{Setup trajectory}\label{setup-trajectory}

Use the \texttt{amt} package to create a trajectory object from the
cleaned data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{buffalo\_all }\OtherTok{\textless{}{-}}\NormalTok{ buffalo\_clean }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{mk\_track}\NormalTok{(}\AttributeTok{id =}\NormalTok{ id,}
\NormalTok{                                          lon,}
\NormalTok{                                          lat, }
\NormalTok{                                          time, }
                                          \AttributeTok{all\_cols =}\NormalTok{ T,}
                                          \AttributeTok{crs =} \DecValTok{4326}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \CommentTok{\# Transformation to GDA94 / Geoscience Australia Lambert (https://epsg.io/3112)}
  \FunctionTok{transform\_coords}\NormalTok{(}\AttributeTok{crs\_to =} \DecValTok{3112}\NormalTok{, }\AttributeTok{crs\_from =} \DecValTok{4326}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{arrange}\NormalTok{(id) }

\CommentTok{\# Number of IDs and locations}
\NormalTok{buffalo\_all }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n\_ids =} \FunctionTok{n\_distinct}\NormalTok{(id),}
            \AttributeTok{n\_locations =} \FunctionTok{n}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tibble: 1 x 2
  n_ids n_locations
  <int>       <int>
1    13      107554
\end{verbatim}

\subsection{Plot the data coloured by
time}\label{plot-the-data-coloured-by-time}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{buffalo\_all }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ x\_, }\AttributeTok{y =}\NormalTok{ y\_, }\AttributeTok{colour =}\NormalTok{ id)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{size =} \FloatTok{0.1}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{coord\_fixed}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{scale\_x\_continuous}\NormalTok{(}\StringTok{"Easting (m)"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\StringTok{"Northing (m)"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_colour\_viridis\_d}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme\_classic}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"none"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-6-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggsave}\NormalTok{(}\StringTok{"outputs/data\_prep/buffalo\_djelk\_map.png"}\NormalTok{, }
       \AttributeTok{width =} \DecValTok{150}\NormalTok{, }\AttributeTok{height =} \DecValTok{150}\NormalTok{, }\AttributeTok{units =} \StringTok{"mm"}\NormalTok{,  }\AttributeTok{dpi =} \DecValTok{1000}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{Plot a timeline of each
individual}\label{plot-a-timeline-of-each-individual}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{buffalo\_all }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ t\_, }\AttributeTok{y =} \FunctionTok{as.factor}\NormalTok{(id), }\AttributeTok{colour =} \FunctionTok{as.factor}\NormalTok{(id))) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{size =} \FloatTok{0.01}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{scale\_x\_datetime}\NormalTok{(}\StringTok{"Date"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_discrete}\NormalTok{(}\StringTok{"Individual ID"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_colour\_viridis\_d}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme\_classic}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"none"}\NormalTok{,}
        \AttributeTok{axis.text.y =} \FunctionTok{element\_blank}\NormalTok{()) }
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-7-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggsave}\NormalTok{(}\StringTok{"outputs/data\_prep/buffalo\_djelk\_timeline.png"}\NormalTok{, }
       \AttributeTok{width =} \DecValTok{150}\NormalTok{, }\AttributeTok{height =} \DecValTok{150}\NormalTok{, }\AttributeTok{units =} \StringTok{"mm"}\NormalTok{,  }\AttributeTok{dpi =} \DecValTok{600}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{Number of location per
day}\label{number-of-location-per-day}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{buffalo\_daily\_locations }\OtherTok{\textless{}{-}}\NormalTok{ buffalo\_all }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{date =}\NormalTok{ lubridate}\SpecialCharTok{::}\FunctionTok{date}\NormalTok{(t\_)) }\SpecialCharTok{\%\textgreater{}\%} 
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{group\_by}\NormalTok{(date) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{n\_locations =} \FunctionTok{n}\NormalTok{(),}
    \AttributeTok{n\_individuals =} \FunctionTok{n\_distinct}\NormalTok{(id)}
\NormalTok{)}

\NormalTok{buffalo\_daily\_locations }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{() }\SpecialCharTok{+} 
    \FunctionTok{geom\_col}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ date, }\AttributeTok{y =}\NormalTok{ n\_locations), }
             \AttributeTok{fill =} \StringTok{"skyblue"}\NormalTok{) }\SpecialCharTok{+} 
    \FunctionTok{geom\_col}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ date, }\AttributeTok{y =}\NormalTok{ n\_individuals), }
             \AttributeTok{fill =} \StringTok{"orange"}\NormalTok{) }\SpecialCharTok{+} 
    \FunctionTok{scale\_x\_date}\NormalTok{(}\StringTok{"Date"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{scale\_y\_continuous}\NormalTok{(}\StringTok{"Number of IDs/Locations"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{scale\_colour\_viridis\_d}\NormalTok{() }\SpecialCharTok{+}
    \FunctionTok{theme\_classic}\NormalTok{() }\SpecialCharTok{+}
    \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"none"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-8-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggsave}\NormalTok{(}\StringTok{"outputs/data\_prep/buffalo\_djelk\_daily\_locations.png"}\NormalTok{,}
       \AttributeTok{width =} \DecValTok{150}\NormalTok{, }\AttributeTok{height =} \DecValTok{80}\NormalTok{, }\AttributeTok{units =} \StringTok{"mm"}\NormalTok{,  }\AttributeTok{dpi =} \DecValTok{600}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\section{Generating the data to fit a deepSSF
model}\label{generating-the-data-to-fit-a-deepssf-model}

\subsection{Create a steps object to check the step
lengths}\label{create-a-steps-object-to-check-the-step-lengths}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# nest the data by individual}
\NormalTok{buffalo\_all\_nested }\OtherTok{\textless{}{-}}\NormalTok{ buffalo\_all }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{arrange}\NormalTok{(id) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{nest}\NormalTok{(}\AttributeTok{data =} \SpecialCharTok{{-}}\StringTok{"id"}\NormalTok{)}

\NormalTok{buffalo\_all\_nested\_steps }\OtherTok{\textless{}{-}}\NormalTok{ buffalo\_all\_nested }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{steps =} \FunctionTok{map}\NormalTok{(data, }\ControlFlowTok{function}\NormalTok{(x)}
\NormalTok{    x }\SpecialCharTok{\%\textgreater{}\%} 
      \CommentTok{\# track\_resample(rate = hours(1), tolerance = minutes(10)) \%\textgreater{}\%}
      \FunctionTok{steps}\NormalTok{()))}

\CommentTok{\# unnest the data after creating \textquotesingle{}steps\textquotesingle{} objects}
\NormalTok{buffalo\_all\_steps }\OtherTok{\textless{}{-}}\NormalTok{ buffalo\_all\_nested\_steps }\SpecialCharTok{\%\textgreater{}\%} 
\NormalTok{  amt}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(id, steps) }\SpecialCharTok{\%\textgreater{}\%} 
\NormalTok{  amt}\SpecialCharTok{::}\FunctionTok{unnest}\NormalTok{(}\AttributeTok{cols =}\NormalTok{ steps)}

\FunctionTok{head}\NormalTok{(buffalo\_all\_steps)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tibble: 6 x 11
  id       x1_    x2_       y1_       y2_   sl_ direction_p     ta_
* <chr>  <dbl>  <dbl>     <dbl>     <dbl> <dbl>       <dbl>   <dbl>
1 2005  41941. 41969. -1435875. -1435671. 206.        1.43  NA     
2 2005  41969. 41922. -1435671. -1435654.  50.7       2.80   1.37  
3 2005  41922. 41779. -1435654. -1435601. 152.        2.78  -0.0214
4 2005  41779. 41841. -1435601. -1435635.  70.7      -0.507  2.99  
5 2005  41841. 41655. -1435635. -1435604. 188.        2.98  -2.80  
6 2005  41655. 41619. -1435604. -1435608.  37.1      -3.02   0.285 
# i 3 more variables: t1_ <dttm>, t2_ <dttm>, dt_ <drtn>
\end{verbatim}

\subsubsection{Plot step lengths and set the buffer
distance}\label{plot-step-lengths-and-set-the-buffer-distance}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# plot step lengths}
\NormalTok{buffalo\_all\_steps }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(sl\_ }\SpecialCharTok{\textless{}} \DecValTok{2000}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ sl\_), }\CommentTok{\#, bins = 50}
                 \AttributeTok{fill =} \StringTok{"skyblue"}\NormalTok{, }\AttributeTok{colour =} \StringTok{"skyblue"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.75}\NormalTok{) }\SpecialCharTok{+}
  \CommentTok{\# scale\_x\_continuous("Step length (m)") + \#, limits = c({-}25, 1250)}
  \FunctionTok{scale\_x\_log10}\NormalTok{(}\StringTok{"Step length (m)"}\NormalTok{) }\SpecialCharTok{+} \CommentTok{\#, limits = c({-}25, 1250)}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\StringTok{"Density"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Step lengths"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_classic}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-10-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# proportion of steps less than the buffer distance}
\CommentTok{\# the distance should be a multiple of the resolution}
\NormalTok{distance }\OtherTok{\textless{}{-}} \DecValTok{1250}
\NormalTok{res }\OtherTok{\textless{}{-}} \DecValTok{25}

\CommentTok{\# check if multiple of the resolution?}
\NormalTok{distance }\SpecialCharTok{\%\%}\NormalTok{ res }\SpecialCharTok{==} \DecValTok{0}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# buffer distance (add the resolution of the cell/2 as we want a centre cell)}
\NormalTok{buffer }\OtherTok{\textless{}{-}}\NormalTok{ distance }\SpecialCharTok{+}\NormalTok{ (res}\SpecialCharTok{/}\DecValTok{2}\NormalTok{)}

\CommentTok{\# calculate the number of cells in each axis}
\NormalTok{nxn\_cells }\OtherTok{\textless{}{-}}\NormalTok{ buffer}\SpecialCharTok{*}\DecValTok{2}\SpecialCharTok{/}\NormalTok{res}
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}\StringTok{"Number of cells in each axis: "}\NormalTok{, nxn\_cells))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "Number of cells in each axis: 101"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# calculate proportion}
\NormalTok{prop\_steps }\OtherTok{\textless{}{-}}\NormalTok{ buffalo\_all\_steps }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(x2\_ }\SpecialCharTok{{-}}\NormalTok{ x1\_ }\SpecialCharTok{\textgreater{}} \SpecialCharTok{{-}}\NormalTok{buffer }\SpecialCharTok{\&} 
\NormalTok{                                             x2\_ }\SpecialCharTok{{-}}\NormalTok{ x1\_ }\SpecialCharTok{\textless{}}\NormalTok{ buffer }\SpecialCharTok{\&}
\NormalTok{                                             y2\_ }\SpecialCharTok{{-}}\NormalTok{ y1\_ }\SpecialCharTok{\textgreater{}} \SpecialCharTok{{-}}\NormalTok{buffer }\SpecialCharTok{\&} 
\NormalTok{                                             y2\_ }\SpecialCharTok{{-}}\NormalTok{ y1\_ }\SpecialCharTok{\textless{}}\NormalTok{ buffer) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{nrow}\NormalTok{() }\SpecialCharTok{/}\NormalTok{ buffalo\_all\_steps }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{nrow}\NormalTok{()}

\FunctionTok{print}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}\StringTok{"Proportion of steps less than "}\NormalTok{, buffer, }\StringTok{"m in x or y direction: "}\NormalTok{, }\FunctionTok{round}\NormalTok{(prop\_steps, }\DecValTok{4}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "Proportion of steps less than 1262.5m in x or y direction: 0.9637"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# maxmimum distance at corner}
\NormalTok{max\_dist }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(buffer}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ buffer}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}\StringTok{"Maximum distance at corner: "}\NormalTok{, }\FunctionTok{round}\NormalTok{(max\_dist, }\DecValTok{2}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "Maximum distance at corner: 1785.44"
\end{verbatim}

\subsection{Prepare and export data for single layer saving (Python
script)}\label{prepare-and-export-data-for-single-layer-saving-python-script}

We also have another script that saves all local layers as individual
npy arrays, which works better when there are many steps per id (to
prevent large tif files), and can make things a bit easier for training
models with many ids.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{buffalo\_all\_steps\_save }\OtherTok{\textless{}{-}}\NormalTok{ buffalo\_all\_steps }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{mutate}\NormalTok{(}
  
  \AttributeTok{dt\_minute =} \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{round}\NormalTok{(}\FunctionTok{difftime}\NormalTok{(t2\_, t1\_, }\AttributeTok{units =} \StringTok{"mins"}\NormalTok{), }\DecValTok{0}\NormalTok{)),}
  \AttributeTok{dt\_hour =} \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{round}\NormalTok{(}\FunctionTok{difftime}\NormalTok{(t2\_, t1\_, }\AttributeTok{units =} \StringTok{"hours"}\NormalTok{), }\DecValTok{2}\NormalTok{)),}
  
  \CommentTok{\# add the minutes as a decimal to the hour, and the hour as a decimal to the day}
  \AttributeTok{hour\_t1 =} \FunctionTok{round}\NormalTok{(lubridate}\SpecialCharTok{::}\FunctionTok{hour}\NormalTok{(t1\_) }\SpecialCharTok{+}\NormalTok{ lubridate}\SpecialCharTok{::}\FunctionTok{minute}\NormalTok{(t1\_)}\SpecialCharTok{/}\DecValTok{60}\NormalTok{,}\DecValTok{2}\NormalTok{),}
  \AttributeTok{yday\_t1 =} \FunctionTok{round}\NormalTok{(lubridate}\SpecialCharTok{::}\FunctionTok{yday}\NormalTok{(t1\_) }\SpecialCharTok{+}\NormalTok{ lubridate}\SpecialCharTok{::}\FunctionTok{hour}\NormalTok{(t1\_)}\SpecialCharTok{/}\DecValTok{24}\NormalTok{,}\DecValTok{2}\NormalTok{),}
  
  \AttributeTok{hour\_t1\_sin1 =} \FunctionTok{sin}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{hour\_t1}\SpecialCharTok{/}\DecValTok{24}\NormalTok{),}
  \AttributeTok{hour\_t1\_cos1 =} \FunctionTok{cos}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{hour\_t1}\SpecialCharTok{/}\DecValTok{24}\NormalTok{),}
  \AttributeTok{hour\_t1\_sin2 =} \FunctionTok{sin}\NormalTok{(}\DecValTok{4}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{hour\_t1}\SpecialCharTok{/}\DecValTok{24}\NormalTok{),}
  \AttributeTok{hour\_t1\_cos2 =} \FunctionTok{cos}\NormalTok{(}\DecValTok{4}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{hour\_t1}\SpecialCharTok{/}\DecValTok{24}\NormalTok{),}
  
  \AttributeTok{yday\_t1\_sin1 =} \FunctionTok{sin}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{yday\_t1}\SpecialCharTok{/}\FloatTok{365.25}\NormalTok{),}
  \AttributeTok{yday\_t1\_cos1 =} \FunctionTok{cos}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{yday\_t1}\SpecialCharTok{/}\FloatTok{365.25}\NormalTok{),}
  \AttributeTok{yday\_t1\_sin2 =} \FunctionTok{sin}\NormalTok{(}\DecValTok{4}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{yday\_t1}\SpecialCharTok{/}\FloatTok{365.25}\NormalTok{),}
  \AttributeTok{yday\_t1\_cos2 =} \FunctionTok{cos}\NormalTok{(}\DecValTok{4}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{yday\_t1}\SpecialCharTok{/}\FloatTok{365.25}\NormalTok{),}
  
  \CommentTok{\# add the minutes as a decimal to the hour, and the hour as a decimal to the day}
  \AttributeTok{hour\_t2 =} \FunctionTok{round}\NormalTok{(lubridate}\SpecialCharTok{::}\FunctionTok{hour}\NormalTok{(t2\_) }\SpecialCharTok{+}\NormalTok{ lubridate}\SpecialCharTok{::}\FunctionTok{minute}\NormalTok{(t2\_)}\SpecialCharTok{/}\DecValTok{60}\NormalTok{,}\DecValTok{2}\NormalTok{),}
  \AttributeTok{yday\_t2 =} \FunctionTok{round}\NormalTok{(lubridate}\SpecialCharTok{::}\FunctionTok{yday}\NormalTok{(t2\_) }\SpecialCharTok{+}\NormalTok{ lubridate}\SpecialCharTok{::}\FunctionTok{hour}\NormalTok{(t2\_)}\SpecialCharTok{/}\DecValTok{24}\NormalTok{,}\DecValTok{2}\NormalTok{),}
  
  \AttributeTok{bearing =}\NormalTok{ direction\_p,}
  \AttributeTok{bearing\_sin =} \FunctionTok{sin}\NormalTok{(bearing),}
  \AttributeTok{bearing\_cos =} \FunctionTok{cos}\NormalTok{(bearing)}
  
\NormalTok{)}

\NormalTok{buffalo\_all\_steps\_save}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tibble: 107,541 x 28
   id       x1_    x2_       y1_       y2_    sl_ direction_p     ta_
 * <chr>  <dbl>  <dbl>     <dbl>     <dbl>  <dbl>       <dbl>   <dbl>
 1 2005  41941. 41969. -1435875. -1435671. 206.         1.43  NA     
 2 2005  41969. 41922. -1435671. -1435654.  50.7        2.80   1.37  
 3 2005  41922. 41779. -1435654. -1435601. 152.         2.78  -0.0214
 4 2005  41779. 41841. -1435601. -1435635.  70.7       -0.507  2.99  
 5 2005  41841. 41655. -1435635. -1435604. 188.         2.98  -2.80  
 6 2005  41655. 41619. -1435604. -1435608.  37.1       -3.02   0.285 
 7 2005  41619. 41688. -1435608. -1436126. 522.        -1.44   1.58  
 8 2005  41688. 41684. -1436126. -1436119.   8.13       2.10  -2.75  
 9 2005  41684. 41675. -1436119. -1436119.   9.75      -3.13   1.05  
10 2005  41675. 41425. -1436119. -1435938. 308.         2.52  -0.635 
# i 107,531 more rows
# i 20 more variables: t1_ <dttm>, t2_ <dttm>, dt_ <drtn>, dt_minute <dbl>,
#   dt_hour <dbl>, hour_t1 <dbl>, yday_t1 <dbl>, hour_t1_sin1 <dbl>,
#   hour_t1_cos1 <dbl>, hour_t1_sin2 <dbl>, hour_t1_cos2 <dbl>,
#   yday_t1_sin1 <dbl>, yday_t1_cos1 <dbl>, yday_t1_sin2 <dbl>,
#   yday_t1_cos2 <dbl>, hour_t2 <dbl>, yday_t2 <dbl>, bearing <dbl>,
#   bearing_sin <dbl>, bearing_cos <dbl>
\end{verbatim}

\subsection{Save the data to a csv
file}\label{save-the-data-to-a-csv-file}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# remove steps that fall outside of the local spatial extent}
\NormalTok{buffalo\_all\_steps\_save }\OtherTok{\textless{}{-}}\NormalTok{ buffalo\_all\_steps\_save }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(x2\_ }\SpecialCharTok{{-}}\NormalTok{ x1\_ }\SpecialCharTok{\textgreater{}} \SpecialCharTok{{-}}\NormalTok{distance }\SpecialCharTok{\&} 
\NormalTok{           x2\_ }\SpecialCharTok{{-}}\NormalTok{ x1\_ }\SpecialCharTok{\textless{}}\NormalTok{ distance }\SpecialCharTok{\&}
\NormalTok{           y2\_ }\SpecialCharTok{{-}}\NormalTok{ y1\_ }\SpecialCharTok{\textgreater{}} \SpecialCharTok{{-}}\NormalTok{distance }\SpecialCharTok{\&} 
\NormalTok{           y2\_ }\SpecialCharTok{{-}}\NormalTok{ y1\_ }\SpecialCharTok{\textless{}}\NormalTok{ distance) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{drop\_na}\NormalTok{(ta\_)}

\NormalTok{buffalo\_all\_steps\_save}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tibble: 103,558 x 28
   id       x1_    x2_       y1_       y2_    sl_ direction_p     ta_
   <chr>  <dbl>  <dbl>     <dbl>     <dbl>  <dbl>       <dbl>   <dbl>
 1 2005  41969. 41922. -1435671. -1435654.  50.7        2.80   1.37  
 2 2005  41922. 41779. -1435654. -1435601. 152.         2.78  -0.0214
 3 2005  41779. 41841. -1435601. -1435635.  70.7       -0.507  2.99  
 4 2005  41841. 41655. -1435635. -1435604. 188.         2.98  -2.80  
 5 2005  41655. 41619. -1435604. -1435608.  37.1       -3.02   0.285 
 6 2005  41619. 41688. -1435608. -1436126. 522.        -1.44   1.58  
 7 2005  41688. 41684. -1436126. -1436119.   8.13       2.10  -2.75  
 8 2005  41684. 41675. -1436119. -1436119.   9.75      -3.13   1.05  
 9 2005  41675. 41425. -1436119. -1435938. 308.         2.52  -0.635 
10 2005  41425. 40563. -1435938. -1435841. 867.         3.03   0.513 
# i 103,548 more rows
# i 20 more variables: t1_ <dttm>, t2_ <dttm>, dt_ <drtn>, dt_minute <dbl>,
#   dt_hour <dbl>, hour_t1 <dbl>, yday_t1 <dbl>, hour_t1_sin1 <dbl>,
#   hour_t1_cos1 <dbl>, hour_t1_sin2 <dbl>, hour_t1_cos2 <dbl>,
#   yday_t1_sin1 <dbl>, yday_t1_cos1 <dbl>, yday_t1_sin2 <dbl>,
#   yday_t1_cos2 <dbl>, hour_t2 <dbl>, yday_t2 <dbl>, bearing <dbl>,
#   bearing_sin <dbl>, bearing_cos <dbl>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{buffalo\_all\_steps\_save }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{write\_csv}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}\StringTok{"data/buffalo\_djelk\_all\_steps\_nxn"}\NormalTok{, nxn\_cells,}\StringTok{".csv"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

In our case over 96\% of the steps were less than a distance of 1262.5m
in either the x or y direction, which would mean that including 101 x
101 cells (which would be 2525 m x 2525 m) would include at least 96\%
of the steps. As the distance is further to the corner (but still less
than the buffer distance in the x and y directions), there will be step
lengths longer than the buffer distance (up to 1785 m).

\subsection{Read in the environmental
covariates}\label{read-in-the-environmental-covariates}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ndvi\_projected }\OtherTok{\textless{}{-}} \FunctionTok{rast}\NormalTok{(}\StringTok{"mapping/cropped rasters/ndvi\_GEE\_projected\_watermask20230207.tif"}\NormalTok{)}
\NormalTok{terra}\SpecialCharTok{::}\FunctionTok{time}\NormalTok{(ndvi\_projected) }\OtherTok{\textless{}{-}} \FunctionTok{as.POSIXct}\NormalTok{(lubridate}\SpecialCharTok{::}\FunctionTok{ymd}\NormalTok{(}\StringTok{"2018{-}01{-}15"}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{months}\NormalTok{(}\DecValTok{0}\SpecialCharTok{:}\DecValTok{23}\NormalTok{))}
\NormalTok{slope }\OtherTok{\textless{}{-}} \FunctionTok{rast}\NormalTok{(}\StringTok{"mapping/cropped rasters/slope\_raster.tif"}\NormalTok{)}
\NormalTok{veg\_herby }\OtherTok{\textless{}{-}} \FunctionTok{rast}\NormalTok{(}\StringTok{"mapping/cropped rasters/veg\_herby.tif"}\NormalTok{)}
\NormalTok{canopy\_cover }\OtherTok{\textless{}{-}} \FunctionTok{rast}\NormalTok{(}\StringTok{"mapping/cropped rasters/canopy\_cover.tif"}\NormalTok{)}

\CommentTok{\# change the names (these will become the column names when extracting }
\CommentTok{\# covariate values at the used and random steps)}
\FunctionTok{names}\NormalTok{(ndvi\_projected) }\OtherTok{\textless{}{-}} \FunctionTok{rep}\NormalTok{(}\StringTok{"ndvi"}\NormalTok{, terra}\SpecialCharTok{::}\FunctionTok{nlyr}\NormalTok{(ndvi\_projected))}
\FunctionTok{names}\NormalTok{(slope) }\OtherTok{\textless{}{-}} \StringTok{"slope"}
\FunctionTok{names}\NormalTok{(veg\_herby) }\OtherTok{\textless{}{-}} \StringTok{"veg\_herby"}
\FunctionTok{names}\NormalTok{(canopy\_cover) }\OtherTok{\textless{}{-}} \StringTok{"canopy\_cover"}

\CommentTok{\# to plot the rasters}
\FunctionTok{plot}\NormalTok{(ndvi\_projected)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-13-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(ndvi\_projected[[}\DecValTok{1}\NormalTok{]])}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-13-2.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(slope)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-13-3.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(veg\_herby)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-13-4.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(canopy\_cover)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-13-5.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# get the resolution from the covariates}
\NormalTok{res }\OtherTok{\textless{}{-}}\NormalTok{ terra}\SpecialCharTok{::}\FunctionTok{res}\NormalTok{(ndvi\_projected)[}\DecValTok{1}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\subsection{Create some layers for testing the deepSSF
package}\label{create-some-layers-for-testing-the-deepssf-package}

These will be cropped to the extent of the ID 2005 data. We will also
take an average of the NDVI values for simplicity.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{buffer\_distance }\OtherTok{\textless{}{-}} \DecValTok{2500} \CommentTok{\# add a generous buffer distance to ensure we capture all steps for this ID}

\NormalTok{ndvi\_average }\OtherTok{\textless{}{-}}\NormalTok{ terra}\SpecialCharTok{::}\FunctionTok{app}\NormalTok{(ndvi\_projected, mean)}
\FunctionTok{plot}\NormalTok{(ndvi\_average)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-14-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# create a buffer around the buffalo 2005 data}
\NormalTok{buffalo\_clean\_2005\_sf }\OtherTok{\textless{}{-}}\NormalTok{ buffalo\_clean\_2005 }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{st\_as\_sf}\NormalTok{(}\AttributeTok{coords =} \FunctionTok{c}\NormalTok{(}\StringTok{"lon"}\NormalTok{, }\StringTok{"lat"}\NormalTok{), }\AttributeTok{crs =} \DecValTok{4326}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{st\_transform}\NormalTok{(}\AttributeTok{crs =} \DecValTok{3112}\NormalTok{) }

\NormalTok{buffalo\_clean\_2005\_extent }\OtherTok{\textless{}{-}}\NormalTok{ buffalo\_clean\_2005\_sf }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{st\_buffer}\NormalTok{(}\AttributeTok{dist =}\NormalTok{ buffer\_distance) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{st\_bbox}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{st\_as\_sfc}\NormalTok{()}

\CommentTok{\# crop the rasters to the extent of the buffalo 2005 data with the buffer distance}
\NormalTok{ndvi\_2005 }\OtherTok{\textless{}{-}}\NormalTok{ terra}\SpecialCharTok{::}\FunctionTok{crop}\NormalTok{(ndvi\_average, buffalo\_clean\_2005\_extent)}
\NormalTok{slope\_2005 }\OtherTok{\textless{}{-}}\NormalTok{ terra}\SpecialCharTok{::}\FunctionTok{crop}\NormalTok{(slope, buffalo\_clean\_2005\_extent)}

\FunctionTok{plot}\NormalTok{(ndvi\_2005)}
\FunctionTok{points}\NormalTok{(buffalo\_clean\_2005\_sf}\SpecialCharTok{$}\NormalTok{geometry, }\AttributeTok{pch =} \DecValTok{16}\NormalTok{, }\AttributeTok{cex =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-14-2.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(slope\_2005)}
\FunctionTok{points}\NormalTok{(buffalo\_clean\_2005\_sf}\SpecialCharTok{$}\NormalTok{geometry, }\AttributeTok{pch =} \DecValTok{16}\NormalTok{, }\AttributeTok{cex =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-14-3.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# write the rasters to file}
\NormalTok{terra}\SpecialCharTok{::}\FunctionTok{writeRaster}\NormalTok{(ndvi\_2005, }\StringTok{"mapping/cropped rasters/ndvi\_2005.tif"}\NormalTok{, }\AttributeTok{overwrite =}\NormalTok{ T)}
\NormalTok{terra}\SpecialCharTok{::}\FunctionTok{writeRaster}\NormalTok{(slope\_2005, }\StringTok{"mapping/cropped rasters/slope\_2005.tif"}\NormalTok{, }\AttributeTok{overwrite =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\subsection{Set up the spatial extent of the local
covariates}\label{set-up-the-spatial-extent-of-the-local-covariates}

We calculate the number of cells in each axis, and set the lag between
locations. Typically this will just be 1, as we want the next-step to be
the target. However, it may be possible to improve model training by
using different lags and including the time difference between locations
as a covariate. I expect that this would help to predict across
different time scales and not be restricted to the time scale that the
data was collected at.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# calculate the number of cells in each axis}
\NormalTok{nxn\_cells }\OtherTok{\textless{}{-}}\NormalTok{ buffer}\SpecialCharTok{*}\DecValTok{2}\SpecialCharTok{/}\NormalTok{res}
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}\StringTok{"Number of cells in each axis: "}\NormalTok{, nxn\_cells))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "Number of cells in each axis: 101"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# hourly lag {-} to set larger time differences between locations}
\NormalTok{hourly\_lag }\OtherTok{\textless{}{-}} \DecValTok{1}
\end{Highlighting}
\end{Shaded}

\section{Loop over each individual and save the local
rasters}\label{loop-over-each-individual-and-save-the-local-rasters}

This is the main function of the script. It loops over each individual
and calculates step level information, such as the location and time of
the next step (x2, y2, t2), step length, turning angle, and different
time components.

It also determines where to crop the local layers by subtracting and
adding the buffer distance from the location of each step. It then crops
out the local layers for each step and saves them as a list entry into
the data frame.

It then creates a raster stack (with the number of layers equal to the
number of steps) for each covariate and saves it as a tif.

For each individual, this will therefore create a csv containing the
step level information, and a tif for each covariate containing the
local layers for each step.

It takes quite a while to run, around 1 hour per individual in our case,
so we will illustrate the function with 10 steps per individual.
Uncomment the line specified in the loop to use the full dataset.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# for(i in 1:length(buffalo\_ids)) \{}
\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\DecValTok{1}\NormalTok{) \{ }\CommentTok{\# select just the first ID}

\NormalTok{  buffalo\_data }\OtherTok{\textless{}{-}}\NormalTok{ buffalo\_all }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(id }\SpecialCharTok{==}\NormalTok{ buffalo\_ids[i])}
  \CommentTok{\# all data for that individual}
\NormalTok{  buffalo\_data }\OtherTok{\textless{}{-}}\NormalTok{ buffalo\_data }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{arrange}\NormalTok{(t\_)}
  
  \CommentTok{\# to use a subset of the data for that individual for testing}
  \CommentTok{\# COMMENT THIS LINE OUT TO USE THE FULL DATASET}
\NormalTok{  buffalo\_data }\OtherTok{\textless{}{-}}\NormalTok{ buffalo\_data }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{arrange}\NormalTok{(t\_) }\SpecialCharTok{|\textgreater{}}  \FunctionTok{slice}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{100}\NormalTok{)}

\NormalTok{  n\_samples }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(buffalo\_data)}
  
  \FunctionTok{tic}\NormalTok{()}
  
\NormalTok{  buffalo\_data\_covs }\OtherTok{\textless{}{-}}\NormalTok{ buffalo\_data }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{mutate}\NormalTok{(}
    
    \AttributeTok{x1\_ =}\NormalTok{ x\_,}
    \AttributeTok{y1\_ =}\NormalTok{ y\_,}
    \AttributeTok{x2\_ =} \FunctionTok{lead}\NormalTok{(x1\_, }\AttributeTok{n =}\NormalTok{ hourly\_lag, }\AttributeTok{default =} \ConstantTok{NA}\NormalTok{),}
    \AttributeTok{y2\_ =} \FunctionTok{lead}\NormalTok{(y1\_, }\AttributeTok{n =}\NormalTok{ hourly\_lag, }\AttributeTok{default =} \ConstantTok{NA}\NormalTok{),}
    \AttributeTok{x2\_cent =}\NormalTok{ x2\_ }\SpecialCharTok{{-}}\NormalTok{ x1\_,}
    \AttributeTok{y2\_cent =}\NormalTok{ y2\_ }\SpecialCharTok{{-}}\NormalTok{ y1\_,}
    \AttributeTok{t2\_ =} \FunctionTok{lead}\NormalTok{(t\_, }\AttributeTok{n =}\NormalTok{ hourly\_lag, }\AttributeTok{default =} \ConstantTok{NA}\NormalTok{),}
    \AttributeTok{t\_diff =} \FunctionTok{round}\NormalTok{(}\FunctionTok{difftime}\NormalTok{(t2\_, t\_, }\AttributeTok{units =} \StringTok{"hours"}\NormalTok{),}\DecValTok{0}\NormalTok{),}
    
    \CommentTok{\# add the minutes as a decimal to the hour, and the hour as a decimal to the day}
    \AttributeTok{hour\_t1 =} \FunctionTok{round}\NormalTok{(lubridate}\SpecialCharTok{::}\FunctionTok{hour}\NormalTok{(t\_) }\SpecialCharTok{+}\NormalTok{ lubridate}\SpecialCharTok{::}\FunctionTok{minute}\NormalTok{(t\_)}\SpecialCharTok{/}\DecValTok{60}\NormalTok{,}\DecValTok{2}\NormalTok{),}
    \AttributeTok{yday\_t1 =} \FunctionTok{round}\NormalTok{(lubridate}\SpecialCharTok{::}\FunctionTok{yday}\NormalTok{(t\_) }\SpecialCharTok{+}\NormalTok{ lubridate}\SpecialCharTok{::}\FunctionTok{hour}\NormalTok{(t\_)}\SpecialCharTok{/}\DecValTok{24}\NormalTok{,}\DecValTok{2}\NormalTok{),}
    
    \AttributeTok{hour\_t1\_sin1 =} \FunctionTok{sin}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{hour\_t1}\SpecialCharTok{/}\DecValTok{24}\NormalTok{),}
    \AttributeTok{hour\_t1\_cos1 =} \FunctionTok{cos}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{hour\_t1}\SpecialCharTok{/}\DecValTok{24}\NormalTok{),}
    \AttributeTok{hour\_t1\_sin2 =} \FunctionTok{sin}\NormalTok{(}\DecValTok{4}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{hour\_t1}\SpecialCharTok{/}\DecValTok{24}\NormalTok{),}
    \AttributeTok{hour\_t1\_cos2 =} \FunctionTok{cos}\NormalTok{(}\DecValTok{4}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{hour\_t1}\SpecialCharTok{/}\DecValTok{24}\NormalTok{),}
    \AttributeTok{hour\_t1\_sin3 =} \FunctionTok{sin}\NormalTok{(}\DecValTok{6}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{hour\_t1}\SpecialCharTok{/}\DecValTok{24}\NormalTok{),}
    \AttributeTok{hour\_t1\_cos3 =} \FunctionTok{cos}\NormalTok{(}\DecValTok{6}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{hour\_t1}\SpecialCharTok{/}\DecValTok{24}\NormalTok{),}
    
    \AttributeTok{yday\_t1\_sin1 =} \FunctionTok{sin}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{yday\_t1}\SpecialCharTok{/}\FloatTok{365.25}\NormalTok{),}
    \AttributeTok{yday\_t1\_cos1 =} \FunctionTok{cos}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{yday\_t1}\SpecialCharTok{/}\FloatTok{365.25}\NormalTok{),}
    \AttributeTok{yday\_t1\_sin2 =} \FunctionTok{sin}\NormalTok{(}\DecValTok{4}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{yday\_t1}\SpecialCharTok{/}\FloatTok{365.25}\NormalTok{),}
    \AttributeTok{yday\_t1\_cos2 =} \FunctionTok{cos}\NormalTok{(}\DecValTok{4}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{yday\_t1}\SpecialCharTok{/}\FloatTok{365.25}\NormalTok{),}
    \AttributeTok{yday\_t1\_sin3 =} \FunctionTok{sin}\NormalTok{(}\DecValTok{6}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{yday\_t1}\SpecialCharTok{/}\FloatTok{365.25}\NormalTok{),}
    \AttributeTok{yday\_t1\_cos3 =} \FunctionTok{cos}\NormalTok{(}\DecValTok{6}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{yday\_t1}\SpecialCharTok{/}\FloatTok{365.25}\NormalTok{),}
    
    \CommentTok{\# add the minutes as a decimal to the hour, and the hour as a decimal to the day}
    \AttributeTok{hour\_t2 =} \FunctionTok{round}\NormalTok{(lubridate}\SpecialCharTok{::}\FunctionTok{hour}\NormalTok{(t2\_) }\SpecialCharTok{+}\NormalTok{ lubridate}\SpecialCharTok{::}\FunctionTok{minute}\NormalTok{(t2\_)}\SpecialCharTok{/}\DecValTok{60}\NormalTok{,}\DecValTok{2}\NormalTok{),}
    \AttributeTok{hour\_t2\_sin =} \FunctionTok{sin}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{hour\_t2}\SpecialCharTok{/}\DecValTok{24}\NormalTok{),}
    \AttributeTok{hour\_t2\_cos =} \FunctionTok{cos}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{hour\_t2}\SpecialCharTok{/}\DecValTok{24}\NormalTok{),}
    
    \AttributeTok{yday\_t2 =} \FunctionTok{round}\NormalTok{(lubridate}\SpecialCharTok{::}\FunctionTok{yday}\NormalTok{(t2\_) }\SpecialCharTok{+}\NormalTok{ lubridate}\SpecialCharTok{::}\FunctionTok{hour}\NormalTok{(t2\_)}\SpecialCharTok{/}\DecValTok{24}\NormalTok{,}\DecValTok{2}\NormalTok{),}
    \AttributeTok{yday\_t2\_sin =} \FunctionTok{sin}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{yday\_t2}\SpecialCharTok{/}\FloatTok{365.25}\NormalTok{),}
    \AttributeTok{yday\_t2\_cos =} \FunctionTok{cos}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{pi}\SpecialCharTok{*}\NormalTok{yday\_t2}\SpecialCharTok{/}\FloatTok{365.25}\NormalTok{),}
    
    \AttributeTok{sl =} \FunctionTok{c}\NormalTok{(}\FunctionTok{sqrt}\NormalTok{(}\FunctionTok{diff}\NormalTok{(y\_)}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+} \FunctionTok{diff}\NormalTok{(x\_)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{), }\ConstantTok{NA}\NormalTok{),}
    \AttributeTok{log\_sl =} \FunctionTok{log}\NormalTok{(sl),}
    \AttributeTok{bearing =} \FunctionTok{c}\NormalTok{(}\FunctionTok{atan2}\NormalTok{(}\FunctionTok{diff}\NormalTok{(y\_), }\FunctionTok{diff}\NormalTok{(x\_)), }\ConstantTok{NA}\NormalTok{),}
    \AttributeTok{bearing\_sin =} \FunctionTok{sin}\NormalTok{(bearing),}
    \AttributeTok{bearing\_cos =} \FunctionTok{cos}\NormalTok{(bearing),}
    \AttributeTok{ta =} \FunctionTok{c}\NormalTok{(}\ConstantTok{NA}\NormalTok{, }\FunctionTok{ifelse}\NormalTok{(}
      \FunctionTok{diff}\NormalTok{(bearing) }\SpecialCharTok{\textgreater{}}\NormalTok{ pi, }\FunctionTok{diff}\NormalTok{(bearing)}\SpecialCharTok{{-}}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{pi), }\FunctionTok{ifelse}\NormalTok{(}
        \FunctionTok{diff}\NormalTok{(bearing) }\SpecialCharTok{\textless{}} \SpecialCharTok{{-}}\NormalTok{pi, }\FunctionTok{diff}\NormalTok{(bearing)}\SpecialCharTok{+}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{pi), }\FunctionTok{diff}\NormalTok{(bearing)))),}
    \AttributeTok{cos\_ta =} \FunctionTok{cos}\NormalTok{(ta),}
      
    \CommentTok{\# extent for cropping the spatial covariates}
    \AttributeTok{x\_min =}\NormalTok{ x\_ }\SpecialCharTok{{-}}\NormalTok{ buffer,}
    \AttributeTok{x\_max =}\NormalTok{ x\_ }\SpecialCharTok{+}\NormalTok{ buffer,}
    \AttributeTok{y\_min =}\NormalTok{ y\_ }\SpecialCharTok{{-}}\NormalTok{ buffer,}
    \AttributeTok{y\_max =}\NormalTok{ y\_ }\SpecialCharTok{+}\NormalTok{ buffer,}
    
  
    \CommentTok{\# crop out and store the local covariates centered on the animal\textquotesingle{}s location }
    \CommentTok{\# with an extent set in the previous chunk}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{rowwise}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{mutate}\NormalTok{(}

    \CommentTok{\# the extent needs to be the same for saving the stack of rasters}
    \AttributeTok{extent\_00centre =} \FunctionTok{list}\NormalTok{(}\FunctionTok{ext}\NormalTok{(x\_min }\SpecialCharTok{{-}}\NormalTok{ x\_, x\_max }\SpecialCharTok{{-}}\NormalTok{ x\_, y\_min }\SpecialCharTok{{-}}\NormalTok{ y\_, y\_max }\SpecialCharTok{{-}}\NormalTok{ y\_)),}

    \CommentTok{\# NDVI}
    \AttributeTok{ndvi\_index =} \FunctionTok{which.min}\NormalTok{(}\FunctionTok{abs}\NormalTok{(}\FunctionTok{difftime}\NormalTok{(t\_, terra}\SpecialCharTok{::}\FunctionTok{time}\NormalTok{(ndvi\_projected)))),}
    \AttributeTok{ndvi\_cent =} \FunctionTok{list}\NormalTok{(\{}
\NormalTok{      ndvi\_cent }\OtherTok{=} \FunctionTok{crop}\NormalTok{(ndvi\_projected[[ndvi\_index]], }\FunctionTok{ext}\NormalTok{(x\_min, x\_max, y\_min, y\_max))}
      \FunctionTok{ext}\NormalTok{(ndvi\_cent) }\OtherTok{\textless{}{-}}\NormalTok{ extent\_00centre}
\NormalTok{      ndvi\_cent}
\NormalTok{      \}),}

    \CommentTok{\# herbaceous vegetation}
    \AttributeTok{veg\_herby\_cent =} \FunctionTok{list}\NormalTok{(\{}
\NormalTok{      veg\_herby\_cent }\OtherTok{=} \FunctionTok{crop}\NormalTok{(veg\_herby, }\FunctionTok{ext}\NormalTok{(x\_min, x\_max, y\_min, y\_max))}
      \FunctionTok{ext}\NormalTok{(veg\_herby\_cent) }\OtherTok{\textless{}{-}}\NormalTok{ extent\_00centre}
\NormalTok{      veg\_herby\_cent}
\NormalTok{      \}),}

    \CommentTok{\# canopy cover}
    \AttributeTok{canopy\_cover\_cent =} \FunctionTok{list}\NormalTok{(\{}
\NormalTok{      canopy\_cover\_cent }\OtherTok{=} \FunctionTok{crop}\NormalTok{(canopy\_cover, }\FunctionTok{ext}\NormalTok{(x\_min, x\_max, y\_min, y\_max))}
      \FunctionTok{ext}\NormalTok{(canopy\_cover\_cent) }\OtherTok{\textless{}{-}}\NormalTok{ extent\_00centre}
\NormalTok{      canopy\_cover\_cent}
\NormalTok{      \}),}

    \CommentTok{\# slope}
    \AttributeTok{slope\_cent =} \FunctionTok{list}\NormalTok{(\{}
\NormalTok{      slope\_cent }\OtherTok{\textless{}{-}} \FunctionTok{crop}\NormalTok{(slope, }\FunctionTok{ext}\NormalTok{(x\_min, x\_max, y\_min, y\_max))}
      \FunctionTok{ext}\NormalTok{(slope\_cent) }\OtherTok{\textless{}{-}}\NormalTok{ extent\_00centre}
\NormalTok{      slope\_cent}
\NormalTok{      \}),}
    
    \CommentTok{\# presence (next{-}step)}
    \AttributeTok{pres\_template =} \FunctionTok{list}\NormalTok{(\{}
\NormalTok{      pres\_template }\OtherTok{\textless{}{-}} \FunctionTok{crop}\NormalTok{(slope, }\FunctionTok{ext}\NormalTok{(x\_min, x\_max, y\_min, y\_max))}
\NormalTok{      pres\_template}
\NormalTok{    \}),}
    
    \CommentTok{\# Strict within cell method}
    \AttributeTok{points\_vect\_cent\_x2\_within\_cell =} \FunctionTok{list}\NormalTok{(terra}\SpecialCharTok{::}\FunctionTok{vect}\NormalTok{(}\FunctionTok{cbind}\NormalTok{(x2\_, y2\_), }\AttributeTok{type =} \StringTok{"points"}\NormalTok{, }\AttributeTok{crs =} \StringTok{"EPSG:3112"}\NormalTok{)),}
    \AttributeTok{pres\_cent\_x2\_within\_cell =} \FunctionTok{list}\NormalTok{(\{}
\NormalTok{      pres\_cent\_x2\_within\_cell }\OtherTok{\textless{}{-}} \FunctionTok{rasterize}\NormalTok{(points\_vect\_cent\_x2\_within\_cell, pres\_template, }\AttributeTok{background=}\DecValTok{0}\NormalTok{)}
      \FunctionTok{ext}\NormalTok{(pres\_cent\_x2\_within\_cell) }\OtherTok{\textless{}{-}}\NormalTok{ extent\_00centre}
\NormalTok{      pres\_cent\_x2\_within\_cell}
\NormalTok{      \})}
    
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{ungroup}\NormalTok{() }\CommentTok{\# to remove the \textquotesingle{}rowwise\textquotesingle{} class}


  \FunctionTok{toc}\NormalTok{()}

  \CommentTok{\# remove steps that fall outside of the local spatial extent}
\NormalTok{  buffalo\_data\_covs }\OtherTok{\textless{}{-}}\NormalTok{ buffalo\_data\_covs }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{filter}\NormalTok{(x2\_cent }\SpecialCharTok{\textgreater{}} \SpecialCharTok{{-}}\NormalTok{buffer }\SpecialCharTok{\&}\NormalTok{ x2\_cent }\SpecialCharTok{\textless{}}\NormalTok{ buffer }\SpecialCharTok{\&}\NormalTok{ y2\_cent }\SpecialCharTok{\textgreater{}} \SpecialCharTok{{-}}\NormalTok{buffer }\SpecialCharTok{\&}\NormalTok{ y2\_cent }\SpecialCharTok{\textless{}}\NormalTok{ buffer) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{drop\_na}\NormalTok{(ta)}

  \CommentTok{\# remove the columns that are no longer needed}
\NormalTok{  buffalo\_data\_df }\OtherTok{\textless{}{-}}\NormalTok{ buffalo\_data\_covs }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(}
    \SpecialCharTok{{-}}\NormalTok{extent\_00centre,}
    \SpecialCharTok{{-}}\NormalTok{ndvi\_cent,}
    \SpecialCharTok{{-}}\NormalTok{veg\_herby\_cent,}
    \SpecialCharTok{{-}}\NormalTok{canopy\_cover\_cent,}
    \SpecialCharTok{{-}}\NormalTok{slope\_cent,}
    \SpecialCharTok{{-}}\NormalTok{pres\_template,}
    \SpecialCharTok{{-}}\NormalTok{points\_vect\_cent\_x2\_within\_cell,}
    \SpecialCharTok{{-}}\NormalTok{pres\_cent\_x2\_within\_cell)}

  \CommentTok{\# save the data}
  \FunctionTok{write\_csv}\NormalTok{(buffalo\_data\_df, }\FunctionTok{paste0}\NormalTok{(}\StringTok{"buffalo\_local\_data\_id/buffalo\_temporal\_cont\_"}\NormalTok{, buffalo\_ids[i],}
                                    \StringTok{"\_data\_df\_lag\_"}\NormalTok{, hourly\_lag, }\StringTok{"hr\_n"}\NormalTok{, n\_samples, }\StringTok{".csv"}\NormalTok{))}

  \CommentTok{\# saving the raster objects}
  \FunctionTok{rast}\NormalTok{(buffalo\_data\_covs}\SpecialCharTok{$}\NormalTok{ndvi\_cent) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{writeRaster}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}\StringTok{"buffalo\_local\_layers\_id/buffalo\_"}\NormalTok{, buffalo\_ids[i], }\StringTok{"\_ndvi\_cent"}\NormalTok{,}
\NormalTok{                       nxn\_cells, }\StringTok{"x"}\NormalTok{, nxn\_cells, }\StringTok{"\_lag\_"}\NormalTok{, hourly\_lag, }\StringTok{"hr\_n"}\NormalTok{, n\_samples, }\StringTok{".tif"}\NormalTok{),}
                \AttributeTok{overwrite =}\NormalTok{ T)}

  \FunctionTok{rast}\NormalTok{(buffalo\_data\_covs}\SpecialCharTok{$}\NormalTok{veg\_herby\_cent) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{writeRaster}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}\StringTok{"buffalo\_local\_layers\_id/buffalo\_"}\NormalTok{, buffalo\_ids[i], }\StringTok{"\_herby\_cent"}\NormalTok{,}
\NormalTok{                       nxn\_cells, }\StringTok{"x"}\NormalTok{, nxn\_cells, }\StringTok{"\_lag\_"}\NormalTok{, hourly\_lag, }\StringTok{"hr\_n"}\NormalTok{, n\_samples, }\StringTok{".tif"}\NormalTok{),}
                \AttributeTok{overwrite =}\NormalTok{ T)}

  \FunctionTok{rast}\NormalTok{(buffalo\_data\_covs}\SpecialCharTok{$}\NormalTok{canopy\_cover\_cent) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{writeRaster}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}\StringTok{"buffalo\_local\_layers\_id/buffalo\_"}\NormalTok{, buffalo\_ids[i], }\StringTok{"\_canopy\_cent"}\NormalTok{,}
\NormalTok{                       nxn\_cells, }\StringTok{"x"}\NormalTok{, nxn\_cells, }\StringTok{"\_lag\_"}\NormalTok{, hourly\_lag, }\StringTok{"hr\_n"}\NormalTok{, n\_samples, }\StringTok{".tif"}\NormalTok{),}
                \AttributeTok{overwrite =}\NormalTok{ T)}

  \FunctionTok{rast}\NormalTok{(buffalo\_data\_covs}\SpecialCharTok{$}\NormalTok{slope\_cent) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{writeRaster}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}\StringTok{"buffalo\_local\_layers\_id/buffalo\_"}\NormalTok{, buffalo\_ids[i], }\StringTok{"\_slope\_cent"}\NormalTok{,}
\NormalTok{                       nxn\_cells, }\StringTok{"x"}\NormalTok{, nxn\_cells, }\StringTok{"\_lag\_"}\NormalTok{, hourly\_lag, }\StringTok{"hr\_n"}\NormalTok{, n\_samples, }\StringTok{".tif"}\NormalTok{),}
                \AttributeTok{overwrite =}\NormalTok{ T)}

  \FunctionTok{rast}\NormalTok{(buffalo\_data\_covs}\SpecialCharTok{$}\NormalTok{pres\_cent\_x2\_within\_cell) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{writeRaster}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}\StringTok{"buffalo\_local\_layers\_id/within\_cell\_buffalo\_"}\NormalTok{, buffalo\_ids[i], }\StringTok{"\_pres\_cent"}\NormalTok{,}
\NormalTok{                       nxn\_cells, }\StringTok{"x"}\NormalTok{, nxn\_cells, }\StringTok{"\_lag\_"}\NormalTok{, hourly\_lag, }\StringTok{"hr\_n"}\NormalTok{, n\_samples, }\StringTok{".tif"}\NormalTok{),}
                \AttributeTok{overwrite =}\NormalTok{ T)}
  
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
6.304 sec elapsed
\end{verbatim}

\subsection{Check the outputs}\label{check-the-outputs}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(buffalo\_data\_df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tibble: 6 x 44
      x_      y_ t_                  id       x1_     y1_    x2_     y2_ x2_cent
   <dbl>   <dbl> <dttm>              <chr>  <dbl>   <dbl>  <dbl>   <dbl>   <dbl>
1 41969. -1.44e6 2018-07-25 11:04:23 2005  41969. -1.44e6 41922. -1.44e6   -47.8
2 41922. -1.44e6 2018-07-25 12:04:39 2005  41922. -1.44e6 41779. -1.44e6  -142. 
3 41779. -1.44e6 2018-07-25 13:04:17 2005  41779. -1.44e6 41841. -1.44e6    61.8
4 41841. -1.44e6 2018-07-25 14:04:39 2005  41841. -1.44e6 41655. -1.44e6  -186. 
5 41655. -1.44e6 2018-07-25 15:04:27 2005  41655. -1.44e6 41619. -1.44e6   -36.8
6 41619. -1.44e6 2018-07-25 16:04:24 2005  41619. -1.44e6 41688. -1.44e6    69.8
# i 35 more variables: y2_cent <dbl>, t2_ <dttm>, t_diff <drtn>, hour_t1 <dbl>,
#   yday_t1 <dbl>, hour_t1_sin1 <dbl>, hour_t1_cos1 <dbl>, hour_t1_sin2 <dbl>,
#   hour_t1_cos2 <dbl>, hour_t1_sin3 <dbl>, hour_t1_cos3 <dbl>,
#   yday_t1_sin1 <dbl>, yday_t1_cos1 <dbl>, yday_t1_sin2 <dbl>,
#   yday_t1_cos2 <dbl>, yday_t1_sin3 <dbl>, yday_t1_cos3 <dbl>, hour_t2 <dbl>,
#   hour_t2_sin <dbl>, hour_t2_cos <dbl>, yday_t2 <dbl>, yday_t2_sin <dbl>,
#   yday_t2_cos <dbl>, sl <dbl>, log_sl <dbl>, bearing <dbl>, ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(buffalo\_data\_covs)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
# A tibble: 6 x 52
      x_      y_ t_                  id       x1_     y1_    x2_     y2_ x2_cent
   <dbl>   <dbl> <dttm>              <chr>  <dbl>   <dbl>  <dbl>   <dbl>   <dbl>
1 41969. -1.44e6 2018-07-25 11:04:23 2005  41969. -1.44e6 41922. -1.44e6   -47.8
2 41922. -1.44e6 2018-07-25 12:04:39 2005  41922. -1.44e6 41779. -1.44e6  -142. 
3 41779. -1.44e6 2018-07-25 13:04:17 2005  41779. -1.44e6 41841. -1.44e6    61.8
4 41841. -1.44e6 2018-07-25 14:04:39 2005  41841. -1.44e6 41655. -1.44e6  -186. 
5 41655. -1.44e6 2018-07-25 15:04:27 2005  41655. -1.44e6 41619. -1.44e6   -36.8
6 41619. -1.44e6 2018-07-25 16:04:24 2005  41619. -1.44e6 41688. -1.44e6    69.8
# i 43 more variables: y2_cent <dbl>, t2_ <dttm>, t_diff <drtn>, hour_t1 <dbl>,
#   yday_t1 <dbl>, hour_t1_sin1 <dbl>, hour_t1_cos1 <dbl>, hour_t1_sin2 <dbl>,
#   hour_t1_cos2 <dbl>, hour_t1_sin3 <dbl>, hour_t1_cos3 <dbl>,
#   yday_t1_sin1 <dbl>, yday_t1_cos1 <dbl>, yday_t1_sin2 <dbl>,
#   yday_t1_cos2 <dbl>, yday_t1_sin3 <dbl>, yday_t1_cos3 <dbl>, hour_t2 <dbl>,
#   hour_t2_sin <dbl>, hour_t2_cos <dbl>, yday_t2 <dbl>, yday_t2_sin <dbl>,
#   yday_t2_cos <dbl>, sl <dbl>, log_sl <dbl>, bearing <dbl>, ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{which}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(buffalo\_data\_covs}\SpecialCharTok{$}\NormalTok{ta))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
integer(0)
\end{verbatim}

\subsection{Plot a subset of the local
covariates}\label{plot-a-subset-of-the-local-covariates}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n\_plots }\OtherTok{\textless{}{-}} \DecValTok{5}

\CommentTok{\# NDVI}
\FunctionTok{walk}\NormalTok{(buffalo\_data\_covs}\SpecialCharTok{$}\NormalTok{ndvi\_cent[}\DecValTok{1}\SpecialCharTok{:}\NormalTok{n\_plots], terra}\SpecialCharTok{::}\NormalTok{plot)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-2.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-3.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-4.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-5.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Herbaceous vegetation}
\FunctionTok{walk}\NormalTok{(buffalo\_data\_covs}\SpecialCharTok{$}\NormalTok{veg\_herby\_cent[}\DecValTok{1}\SpecialCharTok{:}\NormalTok{n\_plots], terra}\SpecialCharTok{::}\NormalTok{plot)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-6.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-7.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-8.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-9.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-10.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Canopy cover}
\FunctionTok{walk}\NormalTok{(buffalo\_data\_covs}\SpecialCharTok{$}\NormalTok{canopy\_cover\_cent[}\DecValTok{1}\SpecialCharTok{:}\NormalTok{n\_plots], terra}\SpecialCharTok{::}\NormalTok{plot)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-11.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-12.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-13.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-14.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-15.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Slope}
\FunctionTok{walk}\NormalTok{(buffalo\_data\_covs}\SpecialCharTok{$}\NormalTok{slope\_cent[}\DecValTok{1}\SpecialCharTok{:}\NormalTok{n\_plots], terra}\SpecialCharTok{::}\NormalTok{plot)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-16.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-17.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-18.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-19.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-20.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Target (location of the next step)}
\FunctionTok{walk}\NormalTok{(buffalo\_data\_covs}\SpecialCharTok{$}\NormalTok{pres\_cent\_x1[}\DecValTok{1}\SpecialCharTok{:}\NormalTok{n\_plots], terra}\SpecialCharTok{::}\NormalTok{plot)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Warning: Unknown or uninitialised column: `pres_cent_x1`.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Target (location of the next step)}
\FunctionTok{walk}\NormalTok{(buffalo\_data\_covs}\SpecialCharTok{$}\NormalTok{pres\_cent\_x2\_within\_cell[}\DecValTok{1}\SpecialCharTok{:}\NormalTok{n\_plots], terra}\SpecialCharTok{::}\NormalTok{plot)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-21.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-22.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-23.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-24.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-18-25.pdf}}

\subsection{To save the object with all of the local
covariates}\label{to-save-the-object-with-all-of-the-local-covariates}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# saveRDS(buffalo\_data\_covs, paste0("buffalo\_data\_id\_covs\_", Sys.Date(), ".rds"))}
\end{Highlighting}
\end{Shaded}

\subsection{To save some plots}\label{to-save-some-plots}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# for(i in 1:n\_plots) \{}
\CommentTok{\#   png(filename = paste0("ndvi\_cent\_", i, ".png"),}
\CommentTok{\#       width = 150, height = 150, units = "mm", res = 600)}
\CommentTok{\#   terra::plot(buffalo\_data\_covs$ndvi\_cent[[i]])}
\CommentTok{\#   dev.off()}
\CommentTok{\# \}}
\CommentTok{\# }
\CommentTok{\# \# for the pres layers}
\CommentTok{\# for(i in 1:n\_plots) \{}
\CommentTok{\#   }
\CommentTok{\#   \# change the 0 values to NA}
\CommentTok{\#   layer \textless{}{-} buffalo\_data\_covs$pres\_cent[[i]]}
\CommentTok{\#   layer[layer == 0] \textless{}{-} 0.5}
\CommentTok{\#   }
\CommentTok{\#   ndvi\_layer \textless{}{-} buffalo\_data\_covs$ndvi\_cent[[i]]}
\CommentTok{\#   new\_layer \textless{}{-} layer*ndvi\_layer}
\CommentTok{\#   }
\CommentTok{\#   \# save the plot}
\CommentTok{\#   png(filename = paste0("pres\_cent\_", i, ".png"),}
\CommentTok{\#       width = 150, height = 150, units = "mm", res = 600)}
\CommentTok{\#   terra::plot(new\_layer)}
\CommentTok{\#   dev.off()}
\CommentTok{\# \}}
\CommentTok{\# }
\CommentTok{\# }
\CommentTok{\# \# other plots}
\CommentTok{\# }
\CommentTok{\# n\_plots \textless{}{-} 1}
\CommentTok{\# }
\CommentTok{\# for(i in 1:n\_plots) \{}
\CommentTok{\#   png(filename = paste0("veg\_herby\_cent\_", i, ".png"),}
\CommentTok{\#       width = 150, height = 150, units = "mm", res = 600)}
\CommentTok{\#   terra::plot(buffalo\_data\_covs$veg\_herby\_cent[[i]])}
\CommentTok{\#   dev.off()}
\CommentTok{\# \}}
\CommentTok{\# }
\CommentTok{\# for(i in 1:n\_plots) \{}
\CommentTok{\#   png(filename = paste0("canopy\_cover\_cent\_", i, ".png"),}
\CommentTok{\#       width = 150, height = 150, units = "mm", res = 600)}
\CommentTok{\#   terra::plot(buffalo\_data\_covs$canopy\_cover\_cent[[i]])}
\CommentTok{\#   dev.off()}
\CommentTok{\# \}}
\CommentTok{\# }
\CommentTok{\# for(i in 1:n\_plots) \{}
\CommentTok{\#   png(filename = paste0("slope\_cent\_", i, ".png"),}
\CommentTok{\#       width = 150, height = 150, units = "mm", res = 600)}
\CommentTok{\#   terra::plot(buffalo\_data\_covs$slope\_cent[[i]])}
\CommentTok{\#   dev.off()}
\CommentTok{\# \}}
\end{Highlighting}
\end{Shaded}

\subsection{Plot the step lengths and turning
angles}\label{plot-the-step-lengths-and-turning-angles}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# plot step lengths}
\NormalTok{buffalo\_data\_covs }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{ggplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ sl), }
                 \AttributeTok{fill =} \StringTok{"skyblue"}\NormalTok{, }\AttributeTok{colour =} \StringTok{"skyblue"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.75}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_x\_continuous}\NormalTok{(}\StringTok{"Step length (m)"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\StringTok{"Density"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Step lengths"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_classic}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-21-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ggsave("outputs/step\_length.png", height = 60, width = 120, units = "mm", dpi = 600)}


\CommentTok{\# plot turning angles}
\NormalTok{buffalo\_data\_covs }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{ggplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ ta), }
                 \AttributeTok{fill =} \StringTok{"skyblue"}\NormalTok{, }\AttributeTok{colour =} \StringTok{"skyblue"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.75}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_x\_continuous}\NormalTok{(}\StringTok{"Turning angle (radians)"}\NormalTok{, }
    \AttributeTok{breaks =} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{pi, }\SpecialCharTok{{-}}\NormalTok{pi}\SpecialCharTok{/}\DecValTok{2}\NormalTok{, }\DecValTok{0}\NormalTok{, pi}\SpecialCharTok{/}\DecValTok{2}\NormalTok{, pi),}
    \AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\FunctionTok{expression}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{pi), }\FunctionTok{expression}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{pi}\SpecialCharTok{/}\DecValTok{2}\NormalTok{), }\StringTok{"0"}\NormalTok{, }\FunctionTok{expression}\NormalTok{(pi}\SpecialCharTok{/}\DecValTok{2}\NormalTok{), }\FunctionTok{expression}\NormalTok{(pi))}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\StringTok{"Density"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Turning angles"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_classic}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{deepSSF_data_prep_id_files/figure-pdf/unnamed-chunk-21-2.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ggsave("outputs/turning\_angle.png", height = 60, width = 120, units = "mm", dpi = 600)  }
\end{Highlighting}
\end{Shaded}





\end{document}
