---
title: "Getting Started"
author:
  - name: Scott Forrest
    url: https://swforrest.github.io/
    orcid: 0000-0001-9529-0108
    affiliation: Queensland University of Technology, CSIRO
    email: "scottwforrest@gmail.com"
date: today
format: html
---

In this section we provide some guidance for [getting Python set up](python_installation.qmd), a brief introduction to some of the [deep learning concepts](deep_learning_concepts.qmd) that we use in the deepSSF models, some intuition about the [step selection approach](step_selection_intuition.qmd) for modelling animal movement, and then a high-level overview of how we applied those concepts in the [deepSSF model](deepSSF_model_overview.qmd).

In terms of understanding the deepSSF model, the code itself will also be useful, particularly in the [model training](model_training.qmd) and [predictions](predictions.qmd) scripts. These three scripts are written in Python but I've added plots and descriptions along the way that test pieces of code to show what they do (such as the blocks the comprise the deepSSF model). 