---
title: "deepSSF"
format: html
author:
  - name: Scott Forrest
    url: https://swforrest.github.io/
    orcid: 0000-0001-9529-0108
    affiliation: Queensland University of Technology, CSIRO
    email: "scottwforrest@gmail.com"
date: today
bibliography: references.bib
---

This website accompanies the paper '**Predicting animal movement with deepSSF: a deep learning step selection framework**', which can be found on [bioRxiv](https://www.biorxiv.org/content/10.1101/2025.02.13.638055v1).

We created this website to help with understanding the approach, as well as providing all of the code to prepare the data, train a deepSSF model, generate simulations of animal trajectories, assess the trajectories against the observed data, and validate the next-step-ahead predictions against typical SSF models.

The tools for understanding the approach are mostly contained within the navigation tabs at the top, whereas the scripts for everything else are listed in the left sidebar.

For getting started, I suggest visiting the [Step Selection Intuition](step_selection_intuition.qmd) tab first, which walks through the step selection process, making the link to step selection functions (SSFs), which are the foundation for the deepSSF approach. The [deepSSF Model Overview](deepSSF_model_overview.qmd) tab provides information about the deepSSF model that we used (although deep learning is extremely flexible so there are many ways to build the model), and shows an example of what it looks like being trained, and then some simulations from the model. 

There are also many plots and descriptions in the scripts in the left sidebar, particularly in the [deepSSF Training](Python/deepSSF_train.ipynb) script (where the model is fitted to data). I expect that these will also be helpful to understand the approach.

As I (Scott) didn't know Python before getting into this paper, there is a mix of R code (because I'm familiar with it) and Python code (because the deep learning libraries, namely Pytorch, are more developed in it). We are working on applying the deepSSF approach to some other datasets and will be continuing to develop the code, so we may work on translating some scripts the other langauage. There exists [torch for R](https://torch.mlverse.org/), so as far as I'm aware the deepSSF models could also be written in R (although we do have quite a few bespoke components).

As the Python scripts are all written in [Jupyter Notebooks](https://jupyter.org/), it is straightforward to run them in [Google Colab](https://colab.google/), which provides a Python environment as well as access to GPUs. It can be used for free, although when we were training the model many times we paid a small fee for some computing units. The deepSSF models that we built are not big however, and can be run locally on CPU alone in about an hour (which reduces to about 5 mins on a GPU).

![An animation of each step of a simulated trajectory, where the model is trained on Sentinel-2 satellite data and a slope layer, and generates habitat selection and movement (not shown here) predictions, which are combined into the probability of taking the next step. This next-step probability surface is sampled from (location of the white pixel) to become the next step in the trajectory.](figures/simulation_S2.gif)

If you want to get in contact, feel free to reach out to `scottwforrest@gmail.com`, or you can follow me on [Bluesky](https://bsky.app/profile/scottwilliamf.bsky.social).